### ISSUE TITLE
Change Page title subtitle

### ISSUE THREAD

**Issue by themeix** [themeix/html-podcast#11]
**Remove** 
```
<h5 class="fw-normal m-0">Available on Apple Soundcast and Spotify.
                </h5>

```
![image](https://user-images.githubusercontent.com/28748452/116010350-41fab800-a640-11eb-837f-aaa8302d128a.png)

**Add**

```
<p class="lead fw-normal m-0">Available on Apple Soundcast and Spotify.
                </p>

```
![image](https://user-images.githubusercontent.com/28748452/116010333-2b546100-a640-11eb-9c6e-8994ba4a28ff.png)

Use the following code and follow it in other inner pages too,

**Comment by ropangh** [comment]
issue solve

**Comment by themeix** [comment]
Ata to solve hoy nai.. check all pages

**Comment by ropangh** [comment]
c
