### ISSUE TITLE
Add similar type button hover style for all template buttons 

### ISSUE THREAD

**Issue by themeix** [themeix/html-podcast#12]
![image](https://user-images.githubusercontent.com/28748452/116266101-48eb0d00-a79d-11eb-9230-55be8083f870.png)
![image](https://user-images.githubusercontent.com/28748452/116266236-50aab180-a79d-11eb-977e-4b2e6269a896.png)
![image](https://user-images.githubusercontent.com/28748452/116266597-733cca80-a79d-11eb-89ca-41097d09874c.png)
![image](https://user-images.githubusercontent.com/28748452/116266918-c0b93780-a79d-11eb-9568-7a06f324c43b.png)

**Comment by ropangh** [comment]
change
